# Generated by Django 6.0.3 on 2026-03-19 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LichessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lichessUserId', models.CharField(max_length=100)),
                ('lichessUsername', models.CharField(max_length=200)),
                ('access_token', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lichess_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
