# Generated by Django 6.0.3 on 2026-03-14 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('fen', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('evaluation', models.FloatField(blank=True, null=True)),
                ('best_line', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='moves',
            new_name='plies',
        ),
        migrations.AddField(
            model_name='game',
            name='color',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='end_game_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='middle_game_start',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='result',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CriticalMoment',
            fields=[
                ('position_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.position')),
                ('evaluation_delta', models.FloatField(blank=True, null=True)),
            ],
            bases=('main.position',),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='appearances', to='main.position'),
        ),
        migrations.AddField(
            model_name='game',
            name='critical_positions',
            field=models.ManyToManyField(blank=True, related_name='critical_appearances', to='main.criticalmoment'),
        ),
    ]
