# Generated by Django 6.0.3 on 2026-03-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lichesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichesstoken',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lichesstoken',
            name='lichessUserId',
            field=models.CharField(default='----', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lichesstoken',
            name='lichessUsername',
            field=models.CharField(default='DarshJ957', max_length=200),
            preserve_default=False,
        ),
    ]
