# Generated by Django 6.0.3 on 2026-03-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_lichesstoken_last_seen_lichesstoken_lichessuserid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='lichess_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='moves',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_game_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='middle_game_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
