# Generated by Django 6.0.3 on 2026-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_game_lichess_id_game_moves_alter_game_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='chesscom_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='time_control',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='LichessToken',
        ),
    ]
