# Generated by Django 6.0.3 on 2026-03-21 16:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('main', '0007_game_chesscom_id_game_time_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='analysis.analysis'),
        ),
        migrations.AddField(
            model_name='game',
            name='import_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='critical_positions',
            field=models.ManyToManyField(blank=True, related_name='critical_appearances', to='analysis.criticalmoment'),
        ),
        migrations.AlterField(
            model_name='game',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='appearances', to='analysis.position'),
        ),
        migrations.DeleteModel(
            name='CriticalMoment',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
