# Generated by Django 6.0.3 on 2026-04-17 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_analysisresult_taskresult'),
        ('main', '0008_remove_position_user_game_analysed_game_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='critical_positions',
        ),
        migrations.AlterField(
            model_name='game',
            name='analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='analysis.analysisresult'),
        ),
    ]
