# Generated by Django 6.0.3 on 2026-04-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chesscom_username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
