# Generated by Django 6.0.3 on 2026-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_user_chesscom_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opponent',
            field=models.CharField(default='Anonymous', max_length=150),
            preserve_default=False,
        ),
    ]
