# Generated by Django 6.0.3 on 2026-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_game_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moves_uci',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
