# Generated by Django 6.0.3 on 2026-04-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_game_moves_uci'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
