# Generated by Django 6.0.3 on 2026-04-17 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_input', models.JSONField()),
                ('tokens_input', models.IntegerField()),
                ('model_output', models.JSONField()),
                ('tokens_output', models.IntegerField()),
                ('llm_latency', models.FloatField()),
                ('completion_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('task_id', models.CharField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
