# Generated by Django 6.0.3 on 2026-04-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_delete_analysis_rename_number_of_hits_position_hits_and_more'),
        ('main', '0014_remove_game_analysis_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='game',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='main.game'),
        ),
    ]
