# Generated by Django 6.0.3 on 2026-04-30 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_analysisresult_game'),
        ('main', '0014_remove_game_analysis_remove_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='game',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='main.game'),
            preserve_default=False,
        ),
    ]
